In [34]:
import cv2
import numpy as np

img = cv2.imread('cat.jpg', cv2.IMREAD_UNCHANGED)
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) 
print('Original Dimensions : ',img.shape)
shape2 = int(img.shape[0]/2),int(img.shape[1]/2)
resize2 = np.zeros(shape2)
x,y = 0,0
for i in range(0,img.shape[0] -1 ,2):
    y = 0
    for j in range(0,img.shape[1] -1,2):
        resize2[x,y] = img[i,j]
        y = y + 1
    x = x + 1

Original Dimensions :  (415, 640)


In [35]:
scale_percent = 50 # percent of original size
width = int(img.shape[1] * scale_percent / 100)
height = int(img.shape[0] * scale_percent / 100)
dim = (width, height)
  
# resize image
resized = cv2.resize(img, dim,150,33, cv2.INTER_AREA)
 
print('Resized Dimensions : ',resized.shape)

#cv2.imshow("Orignal image", img) 
#cv2.imshow("Resized image", resized)
cv2.imshow("Orignal image", img) 
cv2.imshow("Resized image", resized)
cv2.imshow("My Resize image",resize2)
cv2.waitKey(0)
cv2.destroyAllWindows()

Resized Dimensions :  (207, 320)


In [36]:
#print(img[0:9,0:9])

In [37]:
#print(resized[0:9,0:9])

[[  8.   6.  32. ... 169. 168. 154.]
 [ 13.   7. 114. ... 177. 173. 172.]
 [ 33.  24.  28. ... 184. 177. 169.]
 ...
 [150. 152. 156. ...  90.  87.  69.]
 [146. 149. 155. ...  84.  77.  69.]
 [141. 145. 152. ...  77.  74.  69.]]


In [39]:
print(img)

[[  8   4   6 ... 167 154 140]
 [ 22  23   1 ... 172 165 155]
 [ 13  22   7 ... 175 172 168]
 ...
 [141 143 145 ...  74  69  63]
 [140 141 143 ...  74  68  62]
 [139 140 143 ...  71  66  61]]


In [40]:
print(resize2)

[[  8.   6.  32. ... 169. 168. 154.]
 [ 13.   7. 114. ... 177. 173. 172.]
 [ 33.  24.  28. ... 184. 177. 169.]
 ...
 [150. 152. 156. ...  90.  87.  69.]
 [146. 149. 155. ...  84.  77.  69.]
 [141. 145. 152. ...  77.  74.  69.]]


In [9]:
import numpy
N = int(input())
for Z in range(int(N)):
    line = input()
    lineArr = line.split(' ')
    x,y = int(lineArr[0]),int(lineArr[1])
    array = numpy.zeros((x,y))
    s = 2;
    for i in range(x):
        for j in range(y):
            array[i,j] = int(lineArr[s])
            s = s + 1
    print(array)        
    x,y = int(lineArr[s]),int(lineArr[s+1])
    s = s + 1
    s = s + 1
    array1 = numpy.zeros((x,y))
    for i in range(x):
        for j in range(y):
            array1[i,j] = int(lineArr[s])
            s = s + 1
    print(array1)
    result = numpy.dot(array,array1)
    print(result)

1
2 2 1 1 1 1 2 2 1 1 1 1
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]]


In [54]:
# decalre an array
from itertools import combinations

def comb(arr):
    size = len(arr)
    size = int(size / 2)
    return combinations(arr,size)

def ArrayChallenge(arr):
    combs = comb(arr)
    for i in combs:
        #calculate sum
        sum = 0
        for j in i:
            sum += j
        otherComb = list(set(arr) - set(i)) + list(set(i) - set(arr))
        sum2 = 0
        for k in otherComb:
            sum2 += k
        if sum == sum2:
            return list(i),list(otherComb)
    return -1

def tokken(tokken, result):
    string = ""
    for i in result:
        for k in i:
            string += str(k)
            string += ","
    string += tokken
    #replace every fourth character with underscore
    for i in range(3,len(string),4):
        string = string[:i] + "_" + string[i+1:]
    return string    

In [55]:
arr = [1,2,1,5]

In [59]:
result = ArrayChallenge(arr)
if result != -1:
    tokken("l50msu6ae97",result)
else:
    result = str(result) + "l50msu6ae97"
print(result)

-1l50msu6ae97


In [58]:
ArrayChallenge(arr)

-1